# -*- coding: utf-8 -*-
"""Phishing Detection System Using AI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zYz3rB_zzyEEbQUsIAr8EeX4Y-syDf-N
"""

import gradio as gr
import openai
import re

# OpenAI API Key
openai.api_key = "API_Key"

# GPT model
GPT_MODEL = "gpt-4"

# Users: admin is at index 0
users = [{"email": "admin@example.com", "password": "admin123"}]
user_reports = []
history_data = []
current_user_email = None  # Tracks logged-in user

# Score Prompt
def phishing_email_score_prompt(email_content: str):
    return f"""
You are an intelligent security filter that analyzes emails and calculates a phishing risk **score** based on the presence of red flags or safe features.

Start with a base score of 0%. Then adjust the score according to the following rules. At the end,
respond only with the **final phishing score percentage** as a number between 0 and 100 (e.g., 35%). If the email doesn't have any phishing signs, just return 0.

 **Increase score for phishing features**:
- +30% if the email asks for personal, sensitive, or banking information.
- +10% if it includes urgency tactics (e.g., "verify now", "click here to fix", "act immediately").
- +20% if the email contains grammar mistakes, typos, or awkward sentence structure.
- +15% if it uses generic greetings like "Dear Customer" or doesn't use your name.
- +40% if the message includes a link to click or a downloadable attachment.
- +25% if it contains offers too good to be true (e.g., "You’ve won a prize").

 **Decrease score for legitimate features**:
- −20% if the email uses a specific, personalized greeting.
- −15% if it comes from a known colleague or business partner.
- −50% if the message contains no links or requests for credentials.
- −15% if the content is logical and formal.

Analyze the email and return only the final phishing score as a percentage.
---
Email to Analyze:
{email_content}
---
Respond only with a number (e.g., 60%)
"""

# Reasoning Prompt
def phishing_email_reasoning_prompt(email_content: str, category: str):
    return f"""
You are a cybersecurity assistant. The following email was categorized as: {category}.
Explain briefly why, based on its content. Only include actual features present in the email.
---
Email:
{email_content}
---
"""

# Phishing Detection Function
def detect_phishing(sender, subject, body):
    global current_user_email
    full_email = f"From: {sender}\nSubject: {subject}\n\n{body}"
    score_prompt = phishing_email_score_prompt(full_email)

    try:
        score_response = openai.chat.completions.create(
            model=GPT_MODEL,
            messages=[{"role": "user", "content": score_prompt}],
            max_tokens=10,
            temperature=0
        )
        score_text = score_response.choices[0].message.content.strip()
        match = re.search(r'\d{1,3}%', score_text)
        score = int(match.group().replace("%", "")) if match else None

        if score is None:
            return "Unclear score result."
        if score > 100:
            score = 100

        if score <= 30:
            category = "Likely Legitimate"
            explanation = "No phishing indicators were found. This email appears legitimate."
        elif score <= 70:
            category = "Suspicious"
        else:
            category = "Likely Phishing"

        if score > 30:
            reasoning_prompt = phishing_email_reasoning_prompt(full_email, category)
            reasoning_response = openai.chat.completions.create(
                model=GPT_MODEL,
                messages=[{"role": "user", "content": reasoning_prompt}],
                max_tokens=300,
                temperature=0
            )
            explanation = reasoning_response.choices[0].message.content.strip()

        result = f"Phishing Score: {score}%\nCategory: {category}\n\nReasoning:\n{explanation}"
        history_data.append((sender, subject, body, result))
        return result

    except Exception as e:
        return f"Error: {str(e)}"

# Login
def login(email, password):
    global current_user_email
    for i, user in enumerate(users):
        if user["email"] == email and user["password"] == password:
            current_user_email = email
            if i == 0:  # admin
                return "", gr.update(visible=False), gr.update(visible=False), gr.update(visible=True), gr.update(visible=False), gr.update(visible=False), gr.update(visible=False)
            else:
                return "", gr.update(visible=False), gr.update(visible=True), gr.update(visible=False), gr.update(visible=False), gr.update(visible=False), gr.update(visible=False)
    return "Incorrect email or password", gr.update(visible=True), gr.update(visible=False), gr.update(visible=False), gr.update(visible=False), gr.update(visible=False), gr.update(visible=False)

# Create user
def register_user(email, password):
    if any(user["email"] == email for user in users):
        return "Email already registered"
    users.append({"email": email, "password": password})
    return "Account created successfully!"

# Submit report
def submit_report(text):
    global current_user_email
    user_reports.append((current_user_email, text))
    return "", "Thank you for your report!"

# Show reports (admin only)
def view_reports():
    if not user_reports:
        return "No user reports."
    return "\n\n".join([f"From: {email}\nReport: {text}" for email, text in user_reports])

# Show history
def go_to_history():
    if not history_data:
        return gr.update(visible=False), gr.update(value="No scan history found.")
    history_text = "\n".join([
        f"Email {i+1}:\nFrom: {s}\nSubject: {t}\nResult:\n{r}\n{'-'*40}"
        for i, (s, t, b, r) in enumerate(history_data)
    ])
    return gr.update(visible=True), gr.update(value=history_text)

# Clear inputs on navigation
def clear_and_show(show_id):
    return (
        gr.update(value="", visible=(show_id == "login")),
        gr.update(visible=(show_id == "menu")),
        gr.update(value="", visible=(show_id == "admin")),
        gr.update(visible=(show_id == "checker")),
        gr.update(visible=(show_id == "history")),
        gr.update(value="", visible=(show_id == "report")),
        gr.update(visible=(show_id == "help"))
    )

# UI
with gr.Blocks() as demo:
    gr.Markdown("# GPT-4 Phishing Email Detection System")

    login_msg = gr.Textbox(label="", interactive=False, visible=True)
    with gr.Row(visible=True) as login_row:
        email_input = gr.Textbox(label="Email")
        password_input = gr.Textbox(label="Password", type="password")
        login_btn = gr.Button("Login")
        create_email = gr.Textbox(label="New Email")
        create_pass = gr.Textbox(label="New Password", type="password")
        create_btn = gr.Button("Create Account")
        create_msg = gr.Textbox(label="", interactive=False)

    with gr.Column(visible=False) as menu_row:
        gr.Markdown("### Main Menu")
        check_btn = gr.Button("Check Email")
        history_btn = gr.Button("View History")
        report_btn = gr.Button("Report")
        help_btn = gr.Button("Help")
        logout_btn = gr.Button("Logout")

    with gr.Column(visible=False) as admin_row:
        gr.Markdown("### Admin Panel")
        admin_report = gr.Textbox(label="User Reports", lines=20, interactive=False)
        admin_refresh = gr.Button("Refresh Reports")
        admin_logout = gr.Button("Logout")

    with gr.Column(visible=False) as checker_row:
        sender = gr.Textbox(label="Sender")
        subject = gr.Textbox(label="Email Subject")
        body = gr.Textbox(label="Email Body", lines=10)
        detect_btn = gr.Button("Detect Phishing")
        result = gr.Textbox(label="Detection Result", lines=8)
        back1 = gr.Button("Back to Menu")

    with gr.Column(visible=False) as history_row:
        history_display = gr.Textbox(label="Scan History", lines=20)
        back2 = gr.Button("Back to Menu")

    with gr.Column(visible=False) as report_row:
        report_input = gr.Textbox(label="Write your report or feedback", lines=5)
        report_submit = gr.Button("Submit Report")
        report_msg = gr.Textbox(label="", interactive=False)
        back3 = gr.Button("Back to Menu")

    with gr.Column(visible=False) as help_row:
        gr.Textbox(label="How the System Works", lines=12, interactive=False, value="""This system analyzes emails using GPT-4 to detect phishing indicators and gives you a phishing score with an explanation.
The score is based on things like suspicious links, urgency, and grammar. You can report any emails you find suspicious as well.""")
        back4 = gr.Button("Back to Menu")

    # Events
    login_btn.click(login, inputs=[email_input, password_input], outputs=[
        login_msg, login_row, menu_row, admin_row, checker_row, history_row, report_row
    ])
    create_btn.click(register_user, inputs=[create_email, create_pass], outputs=[create_msg])

    logout_btn.click(lambda: clear_and_show("login"), outputs=[
        email_input, menu_row, admin_row, checker_row, history_row, report_input, help_row
    ])
    admin_logout.click(lambda: clear_and_show("login"), outputs=[
        email_input, menu_row, admin_row, checker_row, history_row, report_input, help_row
    ])
    back1.click(lambda: clear_and_show("menu"), outputs=[
        email_input, menu_row, admin_row, checker_row, history_row, report_input, help_row
    ])
    back2.click(lambda: clear_and_show("menu"), outputs=[
        email_input, menu_row, admin_row, checker_row, history_row, report_input, help_row
    ])
    back3.click(lambda: clear_and_show("menu"), outputs=[
        email_input, menu_row, admin_row, checker_row, history_row, report_input, help_row
    ])
    back4.click(lambda: clear_and_show("menu"), outputs=[
        email_input, menu_row, admin_row, checker_row, history_row, report_input, help_row
    ])

    check_btn.click(lambda: clear_and_show("checker"), outputs=[
        email_input, menu_row, admin_row, checker_row, history_row, report_input, help_row
    ])
    history_btn.click(go_to_history, outputs=[history_row, history_display])
    report_btn.click(lambda: clear_and_show("report"), outputs=[
        email_input, menu_row, admin_row, checker_row, history_row, report_input, help_row
    ])
    help_btn.click(lambda: clear_and_show("help"), outputs=[
        email_input, menu_row, admin_row, checker_row, history_row, report_input, help_row
    ])

    detect_btn.click(detect_phishing, inputs=[sender, subject, body], outputs=[result])
    report_submit.click(submit_report, inputs=[report_input], outputs=[report_input, report_msg])
    admin_refresh.click(view_reports, outputs=[admin_report])

demo.launch()